spring.application.name=UNote

server.port=${PORT:8080}

spring.datasource.url=${datasource_url}
spring.datasource.username=${datasource_username}
spring.datasource.password=${datasource_password}
spring.datasource.driver-class-name=${driver_class}

spring.jpa.hibernate.ddl-auto=${ddl-auto}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${hibernate_dialect}

cloudflare.r2.access-key=${access_key}
cloudflare.r2.secret-key=${secret_key}
cloudflare.r2.account-id=${account_id}
cloudflare.r2.bucket=${bucket}
cloudflare.r2.public-url=${public_url}

spring.servlet.multipart.max-file-size=${max_file_size}
spring.servlet.multipart.max-request-size=${max_file_request}
# westly boof
jwt.secret=${jwt_secret}
jwt.expiration=${jwt_expiration}
api.prefix=/api